#include "../Libraries/debugger.h"

void bp(void){};
void bp_INIZIO(void){};
void bp_bhochestrano(void){};
void bp_primoif(){};
void bp_finisce_la_p(){}
void bp_syscall_(void){};
void bp_interval(){};
void bp_godo(){};
void bp_wait(){};
void bp_correct(){};
void memcpy_start(){};
void memcpy_end(){};
void bp_p_inizio(){};
void zombie_process_excp(){};
void bp_finitoIns(){};
void bp_entra_insBlock(){};
void bp_wait2(){};
void bp_ignore(){};